<a href="https://colab.research.google.com/github/elizabethyoo/team_9/blob/data%2Fcdc_covid/CDC_covid_data_vaccinations_agg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas as pd
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# COVID-19 data from CDC

## United States COVID-19 Cases and Deaths by State over Time
Source: https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36

## United States COVID-19 Cases and Deaths by State over Time
Source: https://healthdata.gov/dataset/United-States-COVID-19-Cases-and-Deaths-by-State-o/hiyb-zgc2

In [ ]:
df_vac = pd.read_csv('/content/drive/MyDrive/DS4A/Datasets /COVID_related/COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv')

In [11]:
df_vac.reset_index(drop=True, inplace=True)
df_vac.head(2)

         Date  MMWR_week  ... Additional_Doses_Janssen  Additional_Doses_Unk_Manuf
0  10/19/2021         42  ...                     0.00                        0.00
1  10/19/2021         42  ...                     0.00                        0.00

[2 rows x 69 columns]

In [12]:
#drop week column
df_agg = df_vac.drop(columns='MMWR_week')

In [13]:
df_agg.head(2)

         Date Location  ...  Additional_Doses_Janssen  Additional_Doses_Unk_Manuf
0  10/19/2021       KS  ...                      0.00                        0.00
1  10/19/2021       WY  ...                      0.00                        0.00

[2 rows x 68 columns]

In [14]:
df_agg.Date = pd.to_datetime(df_agg.Date) 
df_agg.head(2)

        Date Location  ...  Additional_Doses_Janssen  Additional_Doses_Unk_Manuf
0 2021-10-19       KS  ...                      0.00                        0.00
1 2021-10-19       WY  ...                      0.00                        0.00

[2 rows x 68 columns]

In [15]:
# group by state then get the monthly mean with resample
# since this is grouping by the mean and not the count, we can only use the Pct (%) features! 
df = df_agg.groupby('Location').resample('M', on = "Date").mean()

In [16]:
df

                     Distributed  ...  Additional_Doses_Unk_Manuf
Location Date                     ...
AK       2020-12-31     36691.67  ...                        0.00
         2021-01-31    131895.16  ...                        0.00
         2021-02-28    274887.68  ...                        0.00
         2021-03-31    486942.10  ...                        0.00
         2021-04-30    716744.00  ...                        0.00
...                          ...  ...                         ...
WY       2021-06-30    511314.67  ...                        0.00
         2021-07-31    521285.65  ...                        0.00
         2021-08-31    553572.42  ...                        0.00
         2021-09-30    628554.00  ...                        0.00
         2021-10-31    687309.74  ...                        0.00

[704 rows x 66 columns]

In [17]:
df.columns

Index(['Distributed', 'Distributed_Janssen', 'Distributed_Moderna',
       'Distributed_Pfizer', 'Distributed_Unk_Manuf', 'Dist_Per_100K',
       'Distributed_Per_100k_12Plus', 'Distributed_Per_100k_18Plus',
       'Distributed_Per_100k_65Plus', 'Administered', 'Administered_12Plus',
       'Administered_18Plus', 'Administered_65Plus', 'Administered_Janssen',
       'Administered_Moderna', 'Administered_Pfizer', 'Administered_Unk_Manuf',
       'Admin_Per_100K', 'Admin_Per_100k_12Plus', 'Admin_Per_100k_18Plus',
       'Admin_Per_100k_65Plus', 'Recip_Administered',
       'Administered_Dose1_Recip', 'Administered_Dose1_Pop_Pct',
       'Administered_Dose1_Recip_12Plus',
       'Administered_Dose1_Recip_12PlusPop_Pct',
       'Administered_Dose1_Recip_18Plus',
       'Administered_Dose1_Recip_18PlusPop_Pct',
       'Administered_Dose1_Recip_65Plus',
       'Administered_Dose1_Recip_65PlusPop_Pct', 'Series_Complete_Yes',
       'Series_Complete_Pop_Pct', 'Series_Complete_12Plus',
       'Series_Complete_12PlusPop_Pct', 'Series_Complete_18Plus',
       'Series_Complete_18PlusPop_Pct', 'Series_Complete_65Plus',
       'Series_Complete_65PlusPop_Pct', 'Series_Complete_Janssen',
       'Series_Complete_Moderna', 'Series_Complete_Pfizer',
       'Series_Complete_Unk_Manuf', 'Series_Complete_Janssen_12Plus',
       'Series_Complete_Moderna_12Plus', 'Series_Complete_Pfizer_12Plus',
       'Series_Complete_Unk_Manuf_12Plus', 'Series_Complete_Janssen_18Plus',
       'Series_Complete_Moderna_18Plus', 'Series_Complete_Pfizer_18Plus',
       'Series_Complete_Unk_Manuf_18Plus', 'Series_Complete_Janssen_65Plus',
       'Series_Complete_Moderna_65Plus', 'Series_Complete_Pfizer_65Plus',
       'Series_Complete_Unk_Manuf_65Plus', 'Additional_Doses',
       'Additional_Doses_Vax_Pct', 'Additional_Doses_18Plus',
       'Additional_Doses_18Plus_Vax_Pct', 'Additional_Doses_50Plus',
       'Additional_Doses_50Plus_Vax_Pct', 'Additional_Doses_65Plus',
       'Additional_Doses_65Plus_Vax_Pct', 'Additional_Doses_Moderna',
       'Additional_Doses_Pfizer', 'Additional_Doses_Janssen',
       'Additional_Doses_Unk_Manuf'],
      dtype='object')

In [20]:
#drop columns that are not % features
df2 = df.drop(columns = ['Distributed', 'Distributed_Janssen', 'Distributed_Moderna',
       'Distributed_Pfizer', 'Distributed_Unk_Manuf', 'Dist_Per_100K',
       'Distributed_Per_100k_12Plus', 'Distributed_Per_100k_18Plus',
       'Distributed_Per_100k_65Plus', 'Administered', 'Administered_12Plus',
       'Administered_18Plus', 'Administered_65Plus', 'Administered_Janssen',
       'Administered_Moderna', 'Administered_Pfizer', 'Administered_Unk_Manuf',
       'Admin_Per_100K', 'Admin_Per_100k_12Plus', 'Admin_Per_100k_18Plus',
       'Admin_Per_100k_65Plus', 'Recip_Administered',
       'Administered_Dose1_Recip',
       'Administered_Dose1_Recip_12Plus',
       'Administered_Dose1_Recip_18Plus',
       'Administered_Dose1_Recip_65Plus','Series_Complete_Yes','Series_Complete_12Plus',
       'Series_Complete_18Plus','Series_Complete_65Plus','Series_Complete_Janssen',
       'Series_Complete_Moderna', 'Series_Complete_Pfizer',
       'Series_Complete_Unk_Manuf', 'Series_Complete_Janssen_12Plus',
       'Series_Complete_Moderna_12Plus', 'Series_Complete_Pfizer_12Plus',
       'Series_Complete_Unk_Manuf_12Plus', 'Series_Complete_Janssen_18Plus',
       'Series_Complete_Moderna_18Plus', 'Series_Complete_Pfizer_18Plus',
       'Series_Complete_Unk_Manuf_18Plus', 'Series_Complete_Janssen_65Plus',
       'Series_Complete_Moderna_65Plus', 'Series_Complete_Pfizer_65Plus',
       'Series_Complete_Unk_Manuf_65Plus', 'Additional_Doses','Additional_Doses_18Plus','Additional_Doses_50Plus',
       'Additional_Doses_65Plus','Additional_Doses_Moderna',
       'Additional_Doses_Pfizer', 'Additional_Doses_Janssen',
       'Additional_Doses_Unk_Manuf'])

In [21]:
df2

                     Administered_Dose1_Pop_Pct  ...  Additional_Doses_65Plus_Vax_Pct
Location Date                                    ...
AK       2020-12-31                        0.00  ...                             0.00
         2021-01-31                        0.00  ...                             0.00
         2021-02-28                       11.39  ...                             0.00
         2021-03-31                       28.48  ...                             0.00
         2021-04-30                       38.42  ...                             0.00
...                                         ...  ...                              ...
WY       2021-06-30                       38.24  ...                             0.00
         2021-07-31                       40.58  ...                             0.00
         2021-08-31                       43.35  ...                             0.00
         2021-09-30                       47.07  ...                             0.00
         2021-10-31                       49.25  ...                             0.00

[704 rows x 12 columns]

In [24]:
root_path = '/content/drive/MyDrive/DS4A/Datasets '

In [25]:
###df2.to_csv(root_path + "/COVID-19_Vaccinations_agg_month.csv")